#!/bin/bash
set -e -o pipefail

delay_min=60
delay_max=90
timeout=15m
propose_exe="$(dirname $0)/rundeck-scripts/propose"

while :; do
	while [[ -z "$(docker ps -q -f name='^rnode$')" ]]; do
		sleep 15
	done

	sleep "$(shuf -n1 -i$delay_min-$delay_max)"
	ret=0
	timeout $timeout $propose_exe || ret=$?
	if (( ret == 124 )); then
		echo "Killed propose after $timeout timeout" >&2
	fi
done
