#!/bin/bash
set -e -o pipefail

delay_min=60
delay_max=90
propose_exe="$(dirname $0)/rundeck-scripts/propose"
env_file=/var/lib/rnode-static/local.autopropose.env

while :; do
	while [[ -z "$(docker ps -q -f name='^rnode$')" ]]; do
		sleep 15
	done

	sleep "$(shuf -n1 -i$delay_min-$delay_max)"

	ret=0
	(
		if [[ -e $env_file ]]; then
			source $env_file
		fi && \
		$propose_exe
	) || ret=$?

	if (( $ret )); then
		echo "Propose exited with error code $ret" >&2
	fi
done
