#!/bin/bash
set -e -o pipefail

interval=60

propose_exe="$(dirname $0)/rundeck-scripts/propose"
env_file=/var/lib/rnode-static/local.autopropose.env

while :; do
	while [[ -z "$(docker ps -q -f name='^rnode$')" ]]; do
		sleep 15
	done

	if [[ -e $env_file ]]; then
		ret=0
		source $env_file || ret=$?
		if (( $ret )); then
			echo "$env_file returned error code $ret" >&2
		fi
	fi

	sleep "$((interval - $(date +%s) % interval))"

	ret=0
	propose_start=$(date +%s)
	$propose_exe || ret=$?
	propose_end=$(date +%s)

	propose_duration=$((propose_end - propose_start))
	collectdctl putval \
		$(hostname -f)/rnode/duration-propose \
		interval=$interval \
		$propose_start:$propose_duration

	if (( $ret )); then
		echo "Propose exited with error code $ret" >&2
	fi
done
