#!/bin/bash
set -e -o pipefail

while :; do
	_hostname="$(hostname -f)"
	if [[ $_hostname == *.* && $_hostname != *.internal ]]; then
		break
	fi
	systemctl restart systemd-networkd
	echo "Waiting for FQDN..."
	sleep 10
done

apt install -y --no-install-recommends \
    apt-transport-https gnupg2 \
    collectd collectd-utils liboping0 jq dnsutils \
	bpfcc-tools iotop \
	openjdk-11-jdk-headless \
	nginx libnginx-mod-http-fancyindex \
	coreutils tree \
	python3 python3-venv build-essential \
	unzip graphviz

# We also require gcloud/gsutil. This is installed on Ubuntu cloud images via
# snap by default. If you disable or remove snap, don't forget to install it via
# other means.

curl -sSfL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
echo 'deb [arch=amd64] https://download.docker.com/linux/ubuntu cosmic stable' \
    >/etc/apt/sources.list.d/docker-ce.list

curl -sSfL https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
echo "deb http://packages.cloud.google.com/apt gcsfuse-bionic main" \
	>/etc/apt/sources.list.d/gcsfuse.list

apt update
apt install -y --no-install-recommends docker-ce gcsfuse

network_dir="node-files${PROFILE:+.$PROFILE}"
node_dir=$network_dir/$(hostname)

install -C -m644 collectd.conf -t /etc/collectd/
systemctl restart collectd

if ! grep -Fq rundeck /root/.ssh/authorized_keys; then
	mkdir -p -m700 /root/.ssh
	cat $network_dir/rundeck-sshid.pub >>/root/.ssh/authorized_keys
fi

mkdir -m710 -p /var/lib/rnode-static
chgrp www-data /var/lib/rnode-static

mkdir -m750 -p /var/lib/rnode-diag
chgrp www-data /var/lib/rnode-diag

install -C -m600 \
	$node_dir/node.key.pem \
	-t /var/lib/rnode-static/

install -C -m644 \
	logback.xml \
	$network_dir/validator-public-keys.txt \
	$node_dir/node.certificate.pem \
	-t /var/lib/rnode-static/

mkdir -m700 -p /var/lib/rnode-static/rnode.conf.d

shopt -s nullglob

install -C -m600 \
	rnode.conf.d/*.conf \
	$network_dir/rnode.conf.d/*.conf \
	$node_dir/rnode.conf.d/*.conf \
	-t /var/lib/rnode-static/rnode.conf.d/

shopt -u nullglob

if [[ -z "$(docker ps -q -f name='^logspout$')" ]]; then
	docker rm logspout || true
	docker pull gliderlabs/logspout
	docker run -d --restart=unless-stopped --name=logspout \
		-p 8181:80 -v /var/run/docker.sock:/var/run/docker.sock \
		gliderlabs/logspout
fi

if ! getent passwd javadebug >/dev/null; then
	useradd -rM -s /bin/false -d /home/javadebug javadebug
	install -m700 -o javadebug -d /home/javadebug
	install -m700 -o javadebug -d /home/javadebug/.ssh
fi
install -C -o javadebug authorized_keys.javadebug /home/javadebug/.ssh/authorized_keys

install -C sshd_config -t /etc/ssh/
systemctl reload sshd

install -C -m644 nginx/* -t /etc/nginx/
systemctl reload nginx

install -d -m755 /usr/lib/systemd/system/
install -C -m644 *.service *.timer -t /usr/lib/systemd/system/

if [[ -f /usr/lib/systemd/system/mnt-heapdumps.mount ]]; then
	systemctl disable --now mnt-heapdumps.mount
	rm /usr/lib/systemd/system/mnt-heapdumps.mount
fi

systemctl daemon-reload

systemctl enable --now sync-diag.timer
systemctl enable --now autopropose.service || true # ignore if masked

pushd scripts >/dev/null
python3 -mvenv venv
source ./venv/bin/activate
pip3 -q install -r requirements.txt
popd >/dev/null

yourkit_version=2019.1
pushd /opt >/dev/null
if [[ ! -e YourKit-JavaProfiler-$yourkit_version ]]; then
	wget -N https://www.yourkit.com/download/docker/YourKit-JavaProfiler-$yourkit_version-docker.zip
	unzip -x YourKit-JavaProfiler-$yourkit_version-docker.zip
	ln -srf YourKit-JavaProfiler-$yourkit_version YourKit-JavaProfiler
fi
popd >/dev/null
