#!/bin/bash
set -e -o pipefail

while [[ "$(hostname -f)" == *.internal ]]; do
	systemctl restart systemd-networkd
	echo "Waiting for FQDN..."
	sleep 5
done

# Due to the issue https://github.com/oetiker/rrdtool-1.x/issues/794
# present in librrd 1.7.0, current version in Ubuntu cosmic/18.10,
# collectd creates files with permissions 0066.
apt install -y librrd8
librrd_ver="$(dpkg-query -W -f '${Version}' librrd8)"
if dpkg --compare-versions $librrd_ver lt '1.7.1'; then
	librrd_url='http://us-central1.gce.archive.ubuntu.com/ubuntu/pool/main/r/rrdtool/librrd8_1.7.1-1_amd64.deb'
	librrd_deb="$(basename "$librrd_url")"
	pushd /tmp
	curl -fsSLO "$librrd_url"
	apt install -y ./$librrd_deb
	rm $librrd_deb
	popd
fi

apt install -y --no-install-recommends \
    apt-transport-https gnupg2 \
    collectd liboping0 jq dnsutils \
	bpfcc-tools iotop \
	openjdk-11-jdk-headless \
	nginx libnginx-mod-http-fancyindex \
	coreutils

curl -sSfL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
echo 'deb [arch=amd64] https://download.docker.com/linux/ubuntu cosmic stable' \
    >/etc/apt/sources.list.d/docker-ce.list

curl -sSfL https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
echo "deb http://packages.cloud.google.com/apt gcsfuse-bionic main" \
	>/etc/apt/sources.list.d/gcsfuse.list

apt update
apt install -y --no-install-recommends docker-ce gcsfuse

install -C -m644 collectd.conf -t /etc/collectd/
systemctl restart collectd

mkdir -p /opt/rdoctor
curl -fsSL -z /opt/rdoctor/rdoctor -o /opt/rdoctor/rdoctor \
	https://build.rchain-dev.tk/misc/rdoctor/latest/linux.amd64/rdoctor
chmod +x /opt/rdoctor/rdoctor

if ! grep -Fq rundeck /root/.ssh/authorized_keys; then
	mkdir -p -m700 /root/.ssh
	cat rundeck-id_rsa.pub >>/root/.ssh/authorized_keys
fi

mkdir -p -m700 /var/lib/rnode-static
files_dir="node-files${PROFILE:+.$PROFILE}"
cp -u $files_dir/$(hostname).*/* /var/lib/rnode-static/
cp -u logback.xml $files_dir/validator-public-keys.txt /var/lib/rnode-static/

mkdir -p /mnt/heapdumps
install -C -m644 mnt-heapdumps.mount -t /etc/systemd/system/
systemctl daemon-reload
systemctl enable --now mnt-heapdumps.mount

if [[ -z "$(docker ps -q -f name='^logspout$')" ]]; then
	docker rm logspout || true
	docker pull gliderlabs/logspout
	docker run -d --restart=unless-stopped --name=logspout \
		-p 8181:80 -v /var/run/docker.sock:/var/run/docker.sock \
		gliderlabs/logspout
fi

if ! getent passwd javadebug >/dev/null; then
	useradd -rM -s /bin/false -d /home/javadebug javadebug
	install -m700 -o javadebug -d /home/javadebug
	install -m700 -o javadebug -d /home/javadebug/.ssh
fi
install -C -o javadebug authorized_keys.javadebug /home/javadebug/.ssh/authorized_keys

install -C sshd_config -t /etc/ssh/
systemctl reload sshd

install -C -m644 nginx/* -t /etc/nginx/
systemctl reload nginx

systemctl link $PWD/autopropose.service
systemctl daemon-reload
systemctl enable --now autopropose
