#!/bin/bash
set -e -o pipefail
source "$(dirname $0)/functions"

local_dir="$1"
[[ -d "$local_dir" ]]

init_diag_variables "$local_dir"
logcmd gsutil rsync -Cdru -j log,txt \
	-x '_index\.html' \
	"$local_dir" "$REMOTE_DIAG_GS_URL"
