#!/bin/bash
set -e -o pipefail
source "$(dirname $0)/functions"

if [[ -z "$RD_OPTION_CONTRACT" ]]; then
	contract="$(docker exec rnode sh -c 'ls ./examples/*.rho' | sort -R | head -1)"
elif [[ "$RD_OPTION_CONTRACT" =~ ^https?:// ]]; then
	contract=/var/lib/rnode-static/rundeck-contract.rho
	logcmd curl -fL -o $contract "$RD_OPTION_CONTRACT"
elif [[ $RD_OPTION_CONTRACT != */* ]]; then
	contract="./examples/$RD_OPTION_CONTRACT"
else
	contract="$RD_OPTION_CONTRACT"
fi

if [[ -z "$contract" ]] || ! docker exec rnode test -f "$contract"; then
	echo "No such contract: '$contract'" >&2
	exit 1
fi

echo "Deploying $contract"
logcmd docker exec rnode ./bin/rnode \
	$RD_OPTION_RNODE_LAUNCHER_ARGS \
	-c /var/lib/rnode-static/rnode.conf \
	deploy \
	--phlo-limit 1000000000 \
	--phlo-price 1 \
	$RD_OPTION_RNODE_DEPLOY_ARGS \
	$contract
