#!/bin/bash
set -e -o pipefail
source "$(dirname $0)/functions"

check_diag_directory
out_file="$DIAG_DIR/heapdump.$(get_current_timestamp).hprof"

java_pid="$(pgrep -x java | tail -1)" || true
if [[ -z "$java_pid" ]]; then
	echo "No java process is running" >&2
else
	logcmd jcmd $java_pid GC.heap_dump "$out_file"
	sync-diag-dir
fi
