#!/bin/bash
set -e -o pipefail
source "$(dirname $0)/functions"

java_pid="$(pgrep -x java | tail -1)" || true

if [[ -z "$java_pid" ]]; then
	echo "No java process is running" >&2
	exit 1
fi

echo "Java process PID: $java_pid"
echo "Output file: $DUMP_PREFIX.hprof"

logcmd jcmd $java_pid GC.heap_dump $DUMP_PREFIX.hprof
