#!/bin/bash
set -e -o pipefail
source "$(dirname $0)/functions"

java_pid="$(pgrep -x java | tail -1)" || true

if [[ -z "$java_pid" ]]; then
	echo "No java process is running" >&2
	exit 1
fi

echo "Java process PID: $java_pid"

filename="$(hostname -f)-$(date -Is|sed 's/+.*//; s/[^0-9-]/-/g').hprof"
echo "Heap dump filename: $filename"

logcmd jcmd $java_pid GC.heap_dump /mnt/heapdumps/$filename
