#!/bin/bash
set -e
source "$(dirname $0)/functions"

echo "Proposing"
ret=0
output="$(docker exec rnode \
	./bin/rnode -c /var/lib/rnode-static/rnode.conf propose 2>&1)" || ret=$?

if [[ $ret -ne 0 && "$output" == *NoNewDeploys* ]]; then
	ret=0
fi

if (( ret )); then
	echo "$output" >&2
else
	echo "$output"
fi
exit $ret
