#!/bin/bash
set -e

if [[ -z "$BASH_SOURCE" ]]; then
	echo "Cannot run from stdin" >&2
	exit 1
fi

if [[ $# -ne 4 ]]; then
	echo "Usage: $0 <nodes-dir> <domain> <network-id> <count>" >&2
	exit 1
fi

out_dir="$1"
domain="$2"
network_id="$3"
count="$4"
scripts_dir="$(dirname "$0")"

cleanup()
{
	rm -r $venv_dir
}
trap cleanup EXIT
venv_dir="$(mktemp -d $(basename "$0").XXXXXXXX)"

python3 -mvenv $venv_dir
source $venv_dir/bin/activate
pip3 install -r "$scripts_dir/requirements.txt"

bootstrap_url=

umask 077
mkdir -p "$out_dir"

for i in $(seq 0 $((count-1))); do
	host=node$i
	node_dir="$out_dir/$host"
	mkdir -p "$node_dir"
	$scripts_dir/generate-node-files $host $network_id "$node_dir" "$bootstrap_url"
	if [[ -z "$bootstrap_url" ]]; then
		bootstrap_url="$(jq -r .rnode.server.bootstrap "$node_dir/rnode.conf")"
	fi
done
