#!/bin/bash
set -e -o pipefail

temp_dir=$(mktemp -d merge-json-fragments.tmpXXXXXXXX)
echo '{}' >$temp_dir/rnode.conf

_log()
{
	if [[ -z $_QUIET ]]; then
		echo "$@" >&2
	fi
}

add_fragment()
{
	fragment=$1
	_log "Adding $fragment"
	jq -s --indent 4 '.[0] * .[1]' $temp_dir/rnode.conf $fragment \
		> $temp_dir/rnode.conf.new
	mv $temp_dir/rnode.conf.new $temp_dir/rnode.conf
}

shopt -s nullglob

for path in "$@"; do
	if [[ -d $path ]]; then
		for file in $path/*.conf; do
			add_fragment $file
		done
	elif [[ -f $path ]]; then
		add_fragment $file
	else
		_log "Path $fragment does not exist"
	fi
done

cat $temp_dir/rnode.conf
rm -r $temp_dir
